import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mergeForecast,formatForecastTime } from '../lib/marine-forecast.ts';
import { buildTimeline,calculateRisk } from '../lib/risk.ts';
const now=Date.parse('2026-10-08T02:30:00Z');
function responses(){const time=Array.from({length:96},(_,i)=>Date.parse('2026-10-07T16:00:00Z')/1000+i*3600);return [
 {latitude:23.5,longitude:119.5,hourly_units:{wave_height:'m',wave_period:'s',ocean_current_velocity:'km/h'},hourly:{time,wave_height:time.map(()=>1.25),wave_period:time.map(()=>6.5),wave_direction:time.map(()=>40),ocean_current_velocity:time.map(()=>3.6)}},
 {latitude:23.55,longitude:119.55,hourly_units:{wind_speed_10m:'m/s'},hourly:{time,wind_speed_10m:time.map(()=>5.25),wind_direction_10m:time.map(()=>80)}}];}
const input={port:{id:'magong',wave:999,period:999,wind:999,current:999,confidence:100,directionRisk:1},boat:'medium',sensitivity:'medium',duration:120,range:72};
test('72 exact hours join on timestamps; units and Taiwan date are correct',()=>{const f=mergeForecast(...responses(),now);assert.equal(f.points.length,72);assert.equal(f.points[0].time,'2026-10-08T02:00:00.000Z');assert.equal(f.points.at(-1).time,'2026-10-11T01:00:00.000Z');assert.equal(f.points[0].current,1);assert.equal(f.points[0].hour,10);assert.match(formatForecastTime(f.points.at(-1).time),/10\/11.*09:00/);});
test('missing marine or wind readings reject the forecast; null is never converted into calm zero',()=>{for(const key of ['wave_height','wave_period']){const [m,w]=responses();m.hourly[key][12]=null;assert.equal(mergeForecast(m,w,now),null);}const [m,w]=responses();w.hourly.wind_speed_10m[12]=null;assert.equal(mergeForecast(m,w,now),null);});
test('missing/mismatched/duplicate timestamps are never filled or paired by index',()=>{for(const change of [a=>a.splice(12,1),a=>a[12]=a[11],a=>a.reverse()]){const [m,w]=responses();change(w.hourly.time);if(w.hourly.time.length===96&&w.hourly.time[0]>w.hourly.time[1]){w.hourly.wind_speed_10m.reverse();w.hourly.wind_direction_10m.reverse();assert.ok(mergeForecast(m,w,now));}else assert.equal(mergeForecast(m,w,now),null);}});
test('optional currents stay missing; unexpected core units fail',()=>{const [m,w]=responses();m.hourly.ocean_current_velocity[12]=null;assert.equal(mergeForecast(m,w,now).points[2].current,null);w.hourly_units.wind_speed_10m='km/h';assert.throws(()=>mergeForecast(m,w,now),/units/);});
test('24h and 72h sample the same API values; old port demo baselines cannot affect risk',()=>{const f=mergeForecast(...responses(),now);const i={...input,forecasts:{magong:f}};const full=buildTimeline(i),short=buildTimeline({...i,range:24});assert.equal(full.length,24);assert.equal(short.length,8);assert.deepEqual(full.slice(0,8),short);assert.equal(short[0].marine.wave,1.25);assert.equal(short[0].marine.wind,5.25);assert.deepEqual(calculateRisk({...i,hourIndex:0}),calculateRisk({...i,port:{...input.port,wave:0,wind:0,confidence:0},hourIndex:0}));});
test('unsupported harbors produce no risk or fake timeline',()=>{assert.equal(calculateRisk({...input,forecasts:{},hourIndex:0}),null);assert.deepEqual(buildTimeline({...input,forecasts:{}}),[]);});
